spring:
    profiles:
        active: prod
    application:
        name: nosql
    data:
        mongodb:
          uri: mongodb+srv://xxx:xxx@yyyy/products 
          
data:
  name: products
  username: XXXXX
  password: XXXX
  
server:
    port: 9000

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG\
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name} 
            
